#!/bin/bash

declare DOTFILES_DIR_PATH="$(dirname $(dirname $(readlink $BASH_SOURCE)))"

# ----------------------------------------------------------------------

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd..='cd ..'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q='exit'
alias c='clear'
alias ch='history -c && > ~/.bash_history'
alias g='git'
alias gp="git pull origin"
alias gc="git commit -m"
alias gpu="git push origin"
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias l='ls -l'
alias m='man'
alias map='xargs -n1'
alias n='npm'
alias y='yarn'
alias q='exit'
alias rm='rm -rf'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases

source "$DOTFILES_DIR_PATH/shell/os_x/bash_aliases"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset DOTFILES_DIR_PATH
unset OS
