#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {

    local file=''
    local i=''

    declare -r -a FILES_TO_SOURCE=(
        'bash_aliases'
        'bash_exports'
        'bash_autocomplete'
        'bash_functions'
        'bash_options'
        'bash_prompt'
        'bash_git'
        'bash.local'  # for local settings that should
                      # not be under version control
    )

    for i in ${!FILES_TO_SOURCE[*]}; do
        file="$HOME/.${FILES_TO_SOURCE[$i]}"
        [ -r "$file" ] && source "$file"
    done

}

source_bash_files
unset -f source_bash_files

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear system messages (e.g.: system copyright notice, the
# date and time of the last login, the message of the day, etc.)

#clear

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/dan/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/dan/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/dan/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/dan/Downloads/google-cloud-sdk/completion.bash.inc'; fi
