#!/bin/bash

eval "$(/opt/homebrew/bin/brew shellenv)"

# Readline
export LDFLAGS="-L/opt/homebrew/opt/readline/lib ${LDFLAGS}"
export CPPFLAGS="-I/opt/homebrew/opt/readline/include ${CPPFLAGS}"
export PKG_CONFIG_PATH="/opt/homebrew/opt/readline/lib/pkgconfig:$PKG_CONFIG_PATH"

# Ruby
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - bash)"

# Node
export REACT_EDITOR="webstorm"
export NVM_DIR="$HOME/.nvm"
export NODE_REPL_HISTORY_SIZE=10000
export PATH="/Applications/WebStorm.app/Contents/MacOS:$PATH"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export PATH="/Users/dan/.flashlight/bin:$PATH"
export PATH="$PATH":"$HOME/.maestro/bin"
nvm use default

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/dan/code/google-cloud-sdk/path.bash.inc' ]; then . '/Users/dan/code/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/dan/code/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/dan/code/google-cloud-sdk/completion.bash.inc'; fi

# Python

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr
export PYTHONIOENCODING='UTF-8'
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
# OpenBLAS
export LDFLAGS="-L/opt/homebrew/opt/openblas/lib ${LDFLAGS}"
export CPPFLAGS="-I/opt/homebrew/opt/openblas/include ${CPPFLAGS}"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig:$PKG_CONFIG_PATH"

# Make vim the default editor
export EDITOR='vim'

# Ignore commands that start with spaces and duplicates
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines of history
# persisted in the Bash history file (default value is 500)
export HISTFILESIZE=10000

# Don't add certain commands to the history file
export HISTIGNORE='&:[bf]g:c:clear:history:exit:q:pwd:* --help'

# Increase the maximum number of commands recorded in the
# command history (default value is 500)
export HISTSIZE=10000

# Prefer US English and use UTF-8 encoding
export LANG='en_US'
export LC_ALL='en_US.UTF-8'

# Use custom `less` colors for man pages
# https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html
export LESS_TERMCAP_md=$'\E[1;32m'   # begin bold mode
export LESS_TERMCAP_me=$'\E[0m'      # end bold mode

# Don't clear the screen after quitting a man page
export MANPAGER='less -X'

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/dan/google-cloud-sdk/path.bash.inc' ]; then . '/Users/dan/google-cloud-sdk/path.bash.inc'; fi

# Android
export PATH="$HOME/.fastlane/bin:$PATH"
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin

#Neo4j
export PATH=$PATH:$ANDROID_HOME/platform-tools

# MySQL client
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

# Docker
export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin/"

# Rust
export PATH=$PATH:$HOME/.cargo/env

# Claude
export PATH="$HOME/.local/bin:$PATH"

# The next line enables shell command completion for gcloud.

if [ -f '/Users/dan/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/dan/google-cloud-sdk/completion.bash.inc'; fi

export BASH_SILENCE_DEPRECATION_WARNING=1

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
